name: Auto Linter
on: 
  push:
    paths: ".github/workflows/*.py"

jobs:
  code: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Code
        uses: actions/checkout@v7
      - name: Install Linter
        run: pip install ruff
      - name: Run Linter
        run: ruff check .
